version: '2'
services:
  mongo:
    restart: always
    image: mongo:4.1.8-xenial
    container_name: mongo_dev
    volumes:     
      - ./.database/mongo/data:/data/db
    ports:
      - "27017:27017"